version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:3000"
    links:
      - mongo
    environment:
      PORT: 3000
  mongo:
    image: mongo
    ports:
      - "27017:27017"